---
author: Oluwafemi OYEDELE
date: '`r format(Sys.Date())`'
title: Analysis of Variance for Buck Afternoon
output:
  html_document:
    toc_float: true
    theme: darkly
    toc: true
fontsize: 12pt
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
```

## Working with Buck Afternoon that has three sheet  

```{r}
library(tidyverse)
library(rio)
library(readxl)
library(agricolae)
library(here)
library(broom)
```

# Import the three sheet as a list into R

```{r}
dat <- import_list(file = here::here('Data/buckAfternoon.xlsx'))
```


# Respiratory rate

```{r}
data1 <- dat[[2]]
data1 <- data1 |> 
  mutate(across(.cols = c(1:5),.fns = factor))


#names <- names(data1[5:50])

#label=paste('RESPRT',sep = '',1:90)
```
# Fit the first model for Respiratory Rate  
```{r}
mod <- lm(RESPRT1~Colour*THIregime,data=data1)
anova(mod)

lala=HSD.test(y = mod,trt = 'Colour',console = TRUE,main = 'Colour')
lala=HSD.test(y = mod,trt = 'THIregime',console = TRUE,main = 'THIregime')
lala=HSD.test(y = mod,trt = c('Colour','THIregime'),console = FALSE)

print(lala)
```
